### PR TITLE
Added Search/Upload for MalShare

### PR DESCRIPTION
**Pull request by silascutler**
Added support for searching and uploading samples to MalShare

### CODE REVIEW

**Comment by diogo-fernan** [comment]
Please modify the code, particularly the `submit_file` function to adhere to all standard practices of module writing, such as defining `api_subf` outside of the function itself.

**Comment by silascutler** [comment]
Cleaned up MalShare submissions.  Please review.

**Comment by diogo-fernan** [comment]
Looks good! Thanks :)

**Review by diogo-fernan — COMMENTED** [review]
Code is now according to the module writing standards.

**Pull request merged**
