### PR TITLE
Set services as deprecated

### PR DESCRIPTION
**Pull request by alex-ilgayev**
Malsub support a large number of services, while few of them became out-of-service during the years.
The incentive to remove inactive services, is to help future refactoring, and reduce amount of irrelevant amount of code.

We don't want to erase the work done writing these services, so I commented them out. You are welcome to suggest any other effective method. (Leaving the code as is will force load it as one of the services, which we don't want)

The services I declared deprecated are:

- AVCaesar - They declared they are discontinuing their service
- malwr - The service is down
- PDF Examiner - The service is down
- QuickSand - The service is down

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
I support removing them completely. The code will be kept in Git History so we shouldn't worry about that.

**Review by ITAYC0HEN — CHANGES_REQUESTED** [review]
I support removing them completely. The code will be kept in Git History so we shouldn't worry about that.

**Comment by diogo-fernan** [comment]
> I support removing them completely. The code will be kept in Git History so we shouldn't worry about that.

Seconded! These may never come back up again, so no worries from my side.

**Review by diogo-fernan — COMMENTED** [review]
Happy to completely remove the services that are no longer around.

**Comment by alex-ilgayev** [comment]
Glad to hear we are agreeing on that.
Possibly more services could be irrelevant, but these ones were obvious. For others, it demands getting proper API keys, which I don't have for all

**Pull request merged**
